export const CREATE_PHARMACY_REQUEST="CREATE_PHARMACY_REQUEST";
export const CREATE_PHARMACY_SUCCESS="CREATE_PHARMACY_SUCCESS";
export const CREATE_PHARMACY_FAILURE="CREATE_PHARMACY_FAILURE";

export const GET_ALL_PHARMACY_REQUEST="GET_ALL_PHARMACY_REQUEST";
export const GET_ALL_PHARMACY_SUCCESS="GET_ALL_PHARMACY_SUCCESS";
export const GET_ALL_PHARMACY_FAILURE="GET_ALL_PHARMACY_FAILURE";

export const DELETE_PHARMACY_REQUEST="DELETE_PHARMACY_REQUEST";
export const DELETE_PHARMACY_SUCCESS="DELETE_PHARMACY_SUCCESS";
export const DELETE_PHARMACY_FAILURE="DELETE_PHARMACY_FAILURE";

export const UPDATE_PHARMACY_REQUEST="UPDATE_PHARMACY_REQUEST";
export const UPDATE_PHARMACY_SUCCESS="UPDATE_PHARMACY_SUCCESS";
export const UPDATE_PHARMACY_FAILURE="UPDATE_PHARMACY_FAILURE";

export const GET_PHARMACY_BY_ID_REQUEST="GET_PHARMACY_BY_ID_REQUEST";
export const GET_PHARMACY_BY_ID_SUCCESS="GET_PHARMACY_BY_ID_SUCCESS";
export const GET_PHARMACY_BY_ID_FAILURE="GET_PHARMACY_BY_ID_FAILURE";

export const GET_PHARMACY_BY_USER_ID_REQUEST="GET_PHARMACY_BY_USER_ID_REQUEST";
export const GET_PHARMACY_BY_USER_ID_SUCCESS="GET_PHARMACY_BY_USER_ID_SUCCESS";
export const GET_PHARMACY_BY_USER_ID_FAILURE="GET_PHARMACY_BY_USER_ID_FAILURE";

export const UPDATE_PHARMACY_STATUS_REQUEST="UPDATE_PHARMACY_STATUS_REQUEST";
export const UPDATE_PHARMACY_STATUS_SUCCESS="UPDATE_PHARMACY_STATUS_SUCCESS";
export const UPDATE_PHARMACY_STATUS_FAILURE="UPDATE_PHARMACY_STATUS_FAILURE";


export const CREATE_CATEGORY_REQUEST="CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS="CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE="CREATE_CATEGORY_FAILURE";

export const GET_PHARMACY_CATEGORY_REQUEST="GET_PHARMACY_CATEGORY_REQUEST";
export const GET_PHARMACY_CATEGORY_SUCCESS="GET_PHARMACY_CATEGORY_SUCCESS";
export const GET_PHARMACY_CATEGORY_FAILURE="GET_PHARMACY_CATEGORY_FAILURE";
