export const UPLOAD_PRESCRIPTION_REQUEST = "UPLOAD_PRESCRIPTION_REQUEST";
export const UPLOAD_PRESCRIPTION_SUCCESS = "UPLOAD_PRESCRIPTION_SUCCESS";
export const UPLOAD_PRESCRIPTION_FAILURE = "UPLOAD_PRESCRIPTION_FAILURE";

export const GET_PRESCRIPTION_REQUEST = "GET_PRESCRIPTION_REQUEST";
export const GET_PRESCRIPTION_SUCCESS = "GET_PRESCRIPTION_SUCCESS";
export const GET_PRESCRIPTION_FAILURE = "GET_PRESCRIPTION_FAILURE";

export const UPDATE_PRESCRIPTION_STATUS_REQUEST = "UPDATE_PRESCRIPTION_STATUS_REQUEST";
export const UPDATE_PRESCRIPTION_STATUS_SUCCESS = "UPDATE_PRESCRIPTION_STATUS_SUCCESS";
export const UPDATE_PRESCRIPTION_STATUS_FAILURE = "UPDATE_PRESCRIPTION_STATUS_FAILURE";

export const DELETE_PRESCRIPTION_REQUEST = "DELETE_PRESCRIPTION_REQUEST";
export const DELETE_PRESCRIPTION_SUCCESS = "DELETE_PRESCRIPTION_SUCCESS";
export const DELETE_PRESCRIPTION_FAILURE = "DELETE_PRESCRIPTION_FAILURE";

export const DOWNLOAD_PRESCRIPTION_REQUEST = "DOWNLOAD_PRESCRIPTION_REQUEST";
export const DOWNLOAD_PRESCRIPTION_SUCCESS = "DOWNLOAD_PRESCRIPTION_SUCCESS";
export const DOWNLOAD_PRESCRIPTION_FAILURE = "DOWNLOAD_PRESCRIPTION_FAILURE";

export const VIEW_PRESCRIPTION_REQUEST = 'VIEW_PRESCRIPTION_REQUEST';
export const VIEW_PRESCRIPTION_SUCCESS = 'VIEW_PRESCRIPTION_SUCCESS';
export const VIEW_PRESCRIPTION_FAILURE = 'VIEW_PRESCRIPTION_FAILURE';