export const GET_DOSSAGE="GET_DOSSAGE";
export const UPDATE_STOCK="UPDATE_STOCK";

export const CREATE_DOSSAGE_REQUEST="CREATE_DOSSAGE_REQUEST";
export const CREATE_DOSSAGE_SUCCESS="CREATE_DOSSAGE_SUCCESS";
export const CREATE_DOSSAGE_FAILURE="CREATE_DOSSAGE_FAILURE";

export const CREATE_DOSSAGE_CATEGORY_REQUEST="CREATE_DOSSAGE_CATEGORY_REQUEST";
export const CREATE_DOSSAGE_CATEGORY_SUCCESS="CREATE_DOSSAGE_CATEGORY_SUCCESS";
export const CREATE_DOSSAGE_CATEGORY_FAILURE="CREATE_INGREDIEN_CATEGORYT_FAILURE";

export const GET_DOSSAGE_CATEGORY_REQUEST="GET_DOSSAGE_CATEGORY_REQUEST";
export const GET_DOSSAGE_CATEGORY_SUCCESS="GET_DOSSAGE_CATEGORY_SUCCESS";
export const GET_DOSSAGE_CATEGORY_FAILURE="GET_INGREDIEN_CATEGORYT_FAILURE";
