
export const ASSIGN_DELIVERY_REQUEST = 'ASSIGN_DELIVERY_REQUEST';
export const ASSIGN_DELIVERY_SUCCESS = 'ASSIGN_DELIVERY_SUCCESS';
export const ASSIGN_DELIVERY_FAIL = 'ASSIGN_DELIVERY_FAIL';

export const UPDATE_DELIVERY_STATUS_SUCCESS = 'UPDATE_DELIVERY_STATUS_SUCCESS';
export const FETCH_DELIVERY_SUCCESS = 'FETCH_DELIVERY_SUCCESS';

export const DELIVERY_FAIL = 'DELIVERY_FAIL';
