
export const CREATE_EVENTS_REQUEST="CREATE_EVENTS_REQUEST";
export const CREATE_EVENTS_SUCCESS="CREATE_EVENTS_SUCCESS";
export const CREATE_EVENTS_FAILURE="CREATE_EVENTS_FAILURE";

export const GET_ALL_EVENTS_REQUEST="GET_ALL_EVENTS_REQUEST";
export const GET_ALL_EVENTS_SUCCESS="GET_ALL_EVENTS_SUCCESS";
export const GET_ALL_EVENTS_FAILURE="GET_ALL_EVENTS_FAILURE";

export const DELETE_EVENTS_REQUEST="DELETE_EVENTS_REQUEST";
export const DELETE_EVENTS_SUCCESS="DELETE_EVENTS_SUCCESS";
export const DELETE_EVENTS_FAILURE="DELETE_EVENTS_FAILURE";

export const GET_PHARMACY_EVENTS_REQUEST="GET_PHARMACY_EVENTS_REQUEST";
export const GET_PHARMACY_EVENTS_SUCCESS="GET_PHARMACY_EVENTS_SUCCESS";
export const GET_PHARMACY_EVENTS_FAILURE="GET_PHARMACY_EVENTS_FAILURE";