export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
export const CLEAR_SEARCH = "CLEAR_SEARCH";

export const SEARCH_PHARMACIES_REQUEST = "SEARCH_PHARMACIES_REQUEST";
export const SEARCH_PHARMACIES_SUCCESS = "SEARCH_PHARMACIES_SUCCESS";
export const SEARCH_PHARMACIES_FAILURE = "SEARCH_PHARMACIES_FAILURE";

export const SEARCH_PHARMACIES_BY_MEDICINE_REQUEST = "SEARCH_PHARMACIES_BY_MEDICINE_REQUEST";
export const SEARCH_PHARMACIES_BY_MEDICINE_SUCCESS = "SEARCH_PHARMACIES_BY_MEDICINE_SUCCESS";
export const SEARCH_PHARMACIES_BY_MEDICINE_FAILURE = "SEARCH_PHARMACIES_BY_MEDICINE_FAILURE";

export const SEARCH_PHARMACIES_BY_CATEGORY_REQUEST = "SEARCH_PHARMACIES_BY_CATEGORY_REQUEST";
export const SEARCH_PHARMACIES_BY_CATEGORY_SUCCESS = "SEARCH_PHARMACIES_BY_CATEGORY_SUCCESS";
export const SEARCH_PHARMACIES_BY_CATEGORY_FAILURE = "SEARCH_PHARMACIES_BY_CATEGORY_FAILURE";

export const SEARCH_MEDICINES_REQUEST = "SEARCH_MEDICINES_REQUEST";
export const SEARCH_MEDICINES_SUCCESS = "SEARCH_MEDICINES_SUCCESS";
export const SEARCH_MEDICINES_FAILURE = "SEARCH_MEDICINES_FAILURE";

export const FILTERED_SEARCH_REQUEST = "FILTERED_SEARCH_REQUEST";
export const FILTERED_SEARCH_SUCCESS = "FILTERED_SEARCH_SUCCESS";
export const FILTERED_SEARCH_FAILURE = "FILTERED_SEARCH_FAILURE";